language: cpp

os: linux
sudo: false
dist: trusty

env:
  global:
    - DEVKITPRO=/opt/devkitpro    
    - DEVKITPPC=/opt/devkitpro/devkitPPC
    - PORTLIBREPOS=$HOME/portlibrepos

cache:
  directories:
    - "$HOME/.local"
    - "$PORTLIBREPOS"
    - "$DEVKITPRO"

addons:
  apt:
    packages:
    - p7zip-full

before_install:
  - mkdir -p "${DEVKITPRO}"
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget https://github.com/devkitPro/pacman/releases/download/devkitpro-pacman-1.0.1/devkitpro-pacman.deb -O /tmp/devkitpro-pacman.deb; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo dpkg -i /tmp/devkitpro-pacman.deb; fi
  - yes | sudo dkp-pacman -Syu devkitPPC
  
install:
  - cd $PORTLIBREPOS
  - (git clone https://github.com/dimok789/libiosuhax.git || (cd libiosuhax && git pull))
  - (cd libiosuhax && make -j8 && make install) 

before_script:
  - cd $TRAVIS_BUILD_DIR/
  
script:
  - make wiiu-install